# roles/tomcat/tasks/manager.yml
---

- name: Install the administration web interface (EL)
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ tomcat_admin_packages }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  notify: restart tomcat
  tags: tomcat

- name: Install the administration web interface (Fedora)
  dnf:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ tomcat_admin_packages }}"
  when: ansible_distribution == "Fedora"
  notify: restart tomcat
  tags: tomcat

- name: Configure users and roles
  template:
    src: etc_tomcat_tomcat-users.xml.j2
    dest: /etc/tomcat/tomcat-users.xml
    mode: '0660'
    owner: tomcat
    group: tomcat
  notify: restart tomcat
  tags: tomcat

